---
- name: Install required PostgreSQL packages
  package:
    name: "{{ postgresql_packages }}"
    state: present
  become: true

- name: Initialize PostgreSQL database
  command: "postgresql-setup initdb"
  become: true
  when: ansible_facts['os_family'] == 'RedHat'

- name: Ensure PostgreSQL config directory exists
  file:
    path: "{{ postgresql_config_file | /home/ubuntu/ }}"
    state: directory
    mode: '0755'
  become: true

- name: Configure PostgreSQL
  template:
    src: postgresql.conf.j2
    dest: "{{ postgresql_config_file }}"
  become: true
  notify:
    - restart postgresql

- name: Ensure PostgreSQL is started and enabled
  service:
    name: "{{ postgresql_service_name }}"
    state: started
    enabled: true
  become: true


